# Generated by Django 5.2.7 on 2025-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(choices=[('Mercedes-Benz', 'Mercedes-Benz'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Toyota', 'Toyota'), ('Other', 'Other')], max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('kilometrage', models.FloatField()),
                ('energy', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Electrique', 'Electrique'), ('Hybride', 'Hybride')], max_length=20)),
                ('boite_vitesse', models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique')], max_length=20)),
                ('puissance_fiscale', models.IntegerField()),
                ('transmission', models.CharField(choices=[('Traction', 'Traction'), ('Propulsion', 'Propulsion'), ('Integrale', 'Integrale')], max_length=20)),
                ('etat_general', models.CharField(choices=[('Excellent', 'Excellent'), ('Bon', 'Bon'), ('Moyen', 'Moyen'), ('Mauvais', 'Mauvais')], max_length=20)),
                ('carrosserie', models.CharField(max_length=50)),
                ('nb_proprietes', models.IntegerField()),
                ('gouvernerat', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='default_car.jpg', upload_to='posts/')),
            ],
        ),
    ]
