# Generated by Django 5.2.8 on 2025-12-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_dashboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='carrosserie',
            field=models.CharField(choices=[('Berline', 'Berline / Sedan'), ('Hatchback', 'Hatchback'), ('Break', 'Break / Station Wagon'), ('Coupé', 'Coupé'), ('Cabriolet', 'Cabriolet / Convertible'), ('SUV', 'SUV / 4x4 / Crossover'), ('Monospace', 'Monospace / Minivan'), ('Pick-up', 'Pick-up / Truck'), ('Utilitaire', 'Utilitaire / Van'), ('Sport', 'Sport'), ('Compacte', 'Compacte'), ('Roadster', 'Roadster'), ('Limousine', 'Limousine'), ('Autres', 'Autres')], default='Berline', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='marque',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Volkswagen', 'Volkswagen'), ('Porsche', 'Porsche'), ('Opel', 'Opel'), ('Maybach', 'Maybach'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Mazda', 'Mazda'), ('Mitsubishi', 'Mitsubishi'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Lexus', 'Lexus'), ('Infiniti', 'Infiniti'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Dodge', 'Dodge'), ('Tesla', 'Tesla'), ('GMC', 'GMC'), ('Jeep', 'Jeep'), ('Cadillac', 'Cadillac'), ('Chrysler', 'Chrysler'), ('Lincoln', 'Lincoln'), ('Buick', 'Buick'), ('Land Rover', 'Land Rover'), ('Range Rover', 'Range Rover'), ('Jaguar', 'Jaguar'), ('Mini', 'Mini'), ('Bentley', 'Bentley'), ('Rolls-Royce', 'Rolls-Royce'), ('Aston Martin', 'Aston Martin'), ('Lotus', 'Lotus'), ('McLaren', 'McLaren'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Maserati', 'Maserati'), ('Alfa Romeo', 'Alfa Romeo'), ('Fiat', 'Fiat'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Citroën', 'Citroën'), ('DS Automobiles', 'DS Automobiles'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Genesis', 'Genesis'), ('Volvo', 'Volvo'), ('Koenigsegg', 'Koenigsegg'), ('BYD', 'BYD'), ('Geely', 'Geely'), ('NIO', 'NIO'), ('Great Wall', 'Great Wall'), ('Changan', 'Changan'), ('Skoda', 'Skoda'), ('SEAT', 'SEAT'), ('Dacia', 'Dacia'), ('Tata', 'Tata'), ('Mahindra', 'Mahindra'), ('Proton', 'Proton'), ('Perodua', 'Perodua'), ('Smart', 'Smart'), ('Other', 'Other')], max_length=100),
        ),
    ]
