# Generated by Django 5.2.8 on 2025-12-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_post_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
