# Generated by Django 5.2.8 on 2025-12-18 13:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advisor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advisoraccess",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="advisoraccess",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="advisoraccess",
            name="paid_at",
        ),
        migrations.RemoveField(
            model_name="advisoraccess",
            name="status",
        ),
        migrations.RemoveField(
            model_name="advisoraccess",
            name="stripe_payment_intent",
        ),
        migrations.AddField(
            model_name="advisoraccess",
            name="active_until",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 18, 13, 34, 6, 575005, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="advisoraccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
