# Generated by Django 5.2.8 on 2025-11-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achats", "0001_initial"),
        ("posts", "0002_alter_post_options_post_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achat",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="achats",
                to="posts.post",
            ),
        ),
    ]
