"""
Django settings for autovolt project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import certifi
load_dotenv()

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p^ej4v$_w2drjf8mx%&(tcph^0z9cy849&awd_wu!4-(wl62s@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'htmlmin',
    "user_app",
    'deals',
    'vehicles',
    'posts',
    'reviews',
    'TestDrive',
    'achats',
    'services',
    'ai_agent',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "autovolt.middleware.BackOfficeAuthMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
]

ROOT_URLCONF = 'autovolt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'autovolt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

HTML_MINIFY = True

KEEP_COMMENTS_ON_MINIFYING = False  # Optional


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "user_app.User"
LOGIN_URL = "login"
LOGOUT_REDIRECT_URL = None
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STRIPE_SECRET_KEY = "sk_test_51SRag7DU2Akojx7VAI9ZbOLJTHu7KkXUaGgLkLiJtm2FcYrz8HrqbUv1iq20yYCg2hjMm6FSnnTkJBYNN6wriEUo00wYLB6jqX"
STRIPE_PUBLIC_KEY = "pk_test_51SRag7DU2Akojx7VyG0tPGiKb3JkfS64NmhmArV2ad89sEigE05Ji2JlEXKQGojSmabZDIhp5ZwmIvq2y6wdmh8w007kZLLNmn"
STRIPE_WEBHOOK_SECRET = ""  # optional until you set webhook
STRIPE_CURRENCY = "usd"  # Stripe doesn't support TND in Checkout; use usd/eur for tests

os.environ["SSL_CERT_FILE"] = certifi.where()


EMAIL_BACKEND = "deals.backends.UnverifiedTLSBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = "fkihomar06122003@gmail.com"
EMAIL_HOST_PASSWORD = "elcs pqrd gkrc dqmp"
DEFAULT_FROM_EMAIL = "DeepDrive <fkihomar06122003@gmail.com>"


TWILIO_ACCOUNT_SID = "ACadf25df9983d77211a47692c31ec6485"
TWILIO_AUTH_TOKEN = "01707a8a4245e2d0794a6eedb848a054"
TWILIO_MESSAGING_SERVICE_SID = "MG48761413776d2391644be162c582092f"

os.environ["SSL_CERT_FILE"] = certifi.where()

EMAIL_BACKEND = "deals.backends.UnverifiedTLSBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = "emnakarray61@gmail.com"
EMAIL_HOST_PASSWORD = "uwve gotm jysk hobm"
DEFAULT_FROM_EMAIL = "DeepDrive <emnakarray61@gmail.com>"

ADMIN_NOTIFICATION_EMAILS = [
    "emnakarray61@gmail.com",
    "fkihomar06122003@gmail.com",
]

