# Generated by Django 5.2.7 on 2025-10-31 16:24

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenariat',
            fields=[
                ('id_partenariat', models.AutoField(db_column='id_partenariat', primary_key=True, serialize=False)),
                ('nom_societe', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('nom_ceo', models.CharField(blank=True, max_length=120, null=True)),
                ('date_partenariat', models.DateField(default=datetime.date.today)),
                ('detail_societe', models.TextField(blank=True, null=True)),
                ('plafond', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_column='status', default='pending', max_length=9)),
                ('user', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partenariat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partenariat',
                'verbose_name_plural': 'Partenariats',
                'db_table': 'partenariat',
            },
        ),
    ]
