# Generated by Django 5.2.7 on 2025-11-04 09:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_prix', models.DecimalField(decimal_places=3, editable=False, max_digits=14)),
                ('taux_rentabilite', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='En %, appliqué sur le total (modifiable côté back si besoin).', max_digits=5)),
                ('rentabilite_estime', models.DecimalField(decimal_places=3, editable=False, max_digits=14)),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marches', to='deals.partenariat')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marches', to='vehicles.voiture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
