# Generated by Django 5.2.8 on 2025-11-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_remove_post_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sold",
            field=models.BooleanField(default=False),
        ),
    ]
