# Generated by Django 5.2.8 on 2025-11-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_post_sold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="sold",
        ),
    ]
