# Generated by Django 5.2.8 on 2025-11-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_remove_post_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="dashboard_image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
