# Generated by Django 5.2.8 on 2025-12-17 11:54

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_alter_post_carrosserie_alter_post_marque"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=512, null=True
            ),
        ),
    ]
