# Generated by Django 5.2.8 on 2025-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_alter_post_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="offer_label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OVERPRICED", "OVERPRICED"),
                    ("NORMAL", "NORMAL"),
                    ("GOOD_DEAL", "GOOD_DEAL"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="predicted_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
    ]
