# Generated by Django 5.2.7 on 2025-11-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for your review (optional)', null=True, upload_to='reviews/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
