# Generated by Django 5.2.7 on 2025-11-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_remove_car_and_update_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(
                default=1, upload_to="reviews/%Y/%m/%d/", verbose_name="Image"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approuvé"),
        ),
        migrations.AlterField(
            model_name="review",
            name="titre",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
    ]
