# Generated by Django 5.2.8 on 2025-11-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_image_alter_review_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date_commentaire',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DateCommentaire'),
        ),
    ]
