# Generated by Django 5.2.8 on 2025-12-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_alter_commentaire_date_commentaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentaire",
            name="sentiment_analyzed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sentiment Analyzed At"
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="sentiment_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Confidence score from 0 to 1",
                null=True,
                verbose_name="Sentiment Confidence",
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="sentiment_label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Positive", "Positive"),
                    ("Neutral", "Neutral"),
                    ("Negative", "Negative"),
                ],
                max_length=20,
                null=True,
                verbose_name="Sentiment",
            ),
        ),
    ]
