# Generated by Django 5.2.7 on 2025-11-16 10:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_marche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenariat',
            name='plafond',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
