# Generated by Django 5.2.7 on 2025-10-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_service', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
                ('garantie', models.CharField(max_length=100)),
                ('type_service', models.CharField(max_length=100)),
                ('type_vidange', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
    ]
