# Generated by Django 5.2.7 on 2025-10-31 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_service',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'La description doit faire au moins 10 caractères.'), django.core.validators.MaxLengthValidator(500, 'La description ne peut pas dépasser 500 caractères.')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='garantie',
            field=models.CharField(choices=[('Sous garantie', 'Sous garantie'), ('Hors garantie', 'Hors garantie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media_service/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Le nom ne doit contenir que des lettres et espaces.')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_service',
            field=models.CharField(choices=[('Entretien', 'Entretien'), ('Réparation', 'Réparation'), ('Diagnostic', 'Diagnostic'), ('Vidange', 'Vidange')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_vidange',
            field=models.CharField(blank=True, choices=[('Huile moteur', 'Huile moteur'), ('Boîte de vitesse', 'Boîte de vitesse')], max_length=50, null=True),
        ),
    ]
