# Generated by Django 5.2.8 on 2025-12-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_remove_advisoraccess_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisorAccess',
        ),
    ]
