# Generated by Django 5.2.7 on 2025-11-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField(blank=True, null=True)),
                ('carrosserie', models.CharField(blank=True, choices=[('berline', 'Berline'), ('suv', 'SUV'), ('citadine', 'Citadine'), ('coupe', 'Coupé'), ('break', 'Break'), ('pickup', 'Pick-up'), ('autre', 'Autre')], max_length=20, null=True)),
                ('nb_place', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nb_porte', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moteur', models.CharField(blank=True, max_length=100, null=True)),
                ('puissance_din', models.FloatField(blank=True, null=True)),
                ('puissance_fiscale', models.FloatField(blank=True, null=True)),
                ('cylindre', models.FloatField(blank=True, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('energy', models.CharField(blank=True, choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique'), ('hybride', 'Hybride'), ('gpl', 'GPL'), ('autre', 'Autre')], max_length=20, null=True)),
                ('boite_vitesse', models.CharField(blank=True, choices=[('manuelle', 'Manuelle'), ('auto', 'Automatique')], max_length=20, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('traction', 'Traction'), ('propulsion', 'Propulsion'), ('integrale', 'Intégrale')], max_length=20, null=True)),
                ('specs', models.JSONField(blank=True, help_text='Attributs libres (clé/valeur).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
