# Generated by Django 5.1 on 2025-12-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True, verbose_name='Analyse IA des dommages'),
        ),
        migrations.AddField(
            model_name='service',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confiance IA (%)'),
        ),
        migrations.AddField(
            model_name='service',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='damage_analysis/', verbose_name='Image avec détections'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_ai_predicted',
            field=models.BooleanField(default=False, verbose_name='Analysé par IA'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media_service/', verbose_name='Photo du véhicule'),
        ),
    ]
