# Generated by Django 5.2.7 on 2025-11-11 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestDrive",
            fields=[
                ("id_test_drive", models.AutoField(primary_key=True, serialize=False)),
                ("reservation_date", models.DateField()),
                ("reservation_time", models.TimeField()),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=30, help_text="Durée du test en minutes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cancelled", "Cancelled"),
                            ("done", "Done"),
                            ("not_done", "Not done"),
                        ],
                        default="not_done",
                        max_length=20,
                    ),
                ),
                (
                    "test_location",
                    models.CharField(
                        choices=[
                            ("Tunis", "Tunis"),
                            ("Ariana", "Ariana"),
                            ("La Marsa", "La Marsa"),
                            ("Carthage", "Carthage"),
                            ("Le Kram", "Le Kram"),
                            ("La Goulette", "La Goulette"),
                            ("Le Bardo", "Le Bardo"),
                            ("Ben Arous", "Ben Arous"),
                            ("Ezzahra", "Ezzahra"),
                            ("Rades", "Rades"),
                            ("Hammam-Lif", "Hammam-Lif"),
                            ("Hammam-Chatt", "Hammam-Chatt"),
                            ("Megrine", "Megrine"),
                            ("Mourouj", "Mourouj"),
                            ("Manouba", "Manouba"),
                            ("Oued Ellil", "Oued Ellil"),
                            ("Douar Hicher", "Douar Hicher"),
                        ],
                        default="Tunis",
                        help_text="Lieu du test drive",
                        max_length=255,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Notes ou remarques du client", null=True
                    ),
                ),
                (
                    "driver_license_number",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de permis du conducteur",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de téléphone du client",
                        max_length=15,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("no_show_history", models.IntegerField(default=0, editable=False)),
                ("reservation_count", models.IntegerField(default=0, editable=False)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_drives",
                        to="vehicles.voiture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_drives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
