# Generated by Django 5.2.8 on 2025-12-17 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestDrive", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="testdrive",
            constraint=models.UniqueConstraint(
                fields=("car", "reservation_date", "reservation_time"),
                name="uniq_testdrive_slot_per_car",
            ),
        ),
    ]
