# Generated by Django 5.2.8 on 2025-12-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchquery",
            name="html",
        ),
        migrations.RemoveField(
            model_name="researchquery",
            name="markdown",
        ),
        migrations.AddField(
            model_name="researchquery",
            name="html_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="researchquery",
            name="markdown_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="researchquery",
            name="pdf_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
